package com.meetfriend.app.utils

object Constant {
    const val LEARN_MORE = "https://www.meeturfriends.com/learn-more"
    const val PRIVACY_POLICY = "https://www.meeturfriends.com/privacy-policy"
    const val TERMS_N_CONDITIONS = "https://www.meeturfriends.com/terms-conditions"
    const val MESSAGE_TYPE_TEXT = "text"
    const val MESSAGE_TYPE_STORY_REPLAY = "reply_story"
    const val MESSAGE_TYPE_KICK_OUT = "kickout"
    const val MESSAGE_TYPE_BAN = "ban"
    const val MESSAGE_TYPE_SLAP = "slap"
    const val AGORA_CHANNEL_NAME_PREFIX = "meet_"
    const val MESSAGE_TYPE_DELETE = "delete"
    const val MESSAGE_TYPE_EDITED = "edited"
    const val MESSAGE_TYPE_SAVE = "save"
    const val MESSAGE_TYPE_FORWARD = "forward"
    const val MESSAGE_TYPE_IMAGE = "image"
    const val MESSAGE_TYPE_REPLY = "reply"
    const val PHOTO = "photo"
    const val VIDEO = "video"
    const val MESSAGE_TYPE_JOIN = "join"
    const val MESSAGE_TYPE_LEFT = "left"

    const val MESSAGE_TYPE_RESTRICT = "restrict"
    const val MESSAGE_TYPE_SEND_GIFT = "send_gift"
    const val MESSAGE_TYPE_REQUEST_GIFT = "request_coins"
    const val TOKEN = "token"
    const val LIKE = "like"
    const val UNLIKE = "unlike"
    const val CALL_TYPE_MISSED = "missed"
    const val CALL_TYPE_VIDEO = "video"
    const val CALL_TYPE_CALLING = "calling"
    const val TYPE_SHORTS = "shorts"
    const val UNBLOCK_STATUS = "unblock"
    const val GAME_RESULT_WIN = "win"
    const val GAME_RESULT_LOSS = "loss"
    const val GAME_RESULT_DRAW = "draw"
    const val JOIN_CHALLENGE = "Join Challenge"
    const val DOWNLOAD_SHORTS = "Download Shorts"
    const val ADD_STORY = "Add Story"
    const val REPOST_POST = "Repost Post"
    const val SEND_GIFT = "Send Gift"
    const val REPORT_CONTENT = "Report Content"
    const val SHARE_CONTENT = "Share Content"
    const val COMMENT_CONTENT = "Comment Content"
    const val LIKE_CONTENT = "Like Content"
    const val SCREEN_TIME = "Screen Time"
    const val TOTAL_HOURS_USER_LIVE_IN_THIS_MONTH = "Total hours user live in this month"

    // Mix panel params
    const val CHALLENGE_ID = "challenge_id"
    const val POST_ID = "post_id"
    const val SHORTS_ID = "shorts_id"
    const val CONTENT_TYPE = "content_type"
    const val CONTENT_ID = "content_id"
    const val SCREEN_TYPE = "screen_type"
    const val LIVE_ID = "live_id"
    const val ROLE = "role"
    const val START_TIME = "start_time"
    const val END_TIME = "end_time"
    const val TOTAL_TIME_OF_THIS_MONTH = "total_time_of_this_month"

    var EXCHANGE_RATE = "1.0"
    var CENT_VALUE = "0.0032"
    var CURRENCY_SYMBOL = "$"
    var CLICK_COUNT = 0

    // Report For
    const val SHORT = "short"
    const val STORY = "story"
    const val POST = "post"
    const val LIVE = "live"
    const val DISMISS = "dismiss"
    const val FiXED_200_MILLISECOND = 200L
    const val FiXED_100_MILLISECOND = 100L
    const val FiXED_1000_MILLISECOND = 1000L
    const val FiXED_2000_MILLISECOND = 2000L
    const val FiXED_3000_MILLISECOND = 3000L
    const val FiXED_4000_MILLISECOND = 4000L
    const val FiXED_5000_MILLISECOND = 5000L
    const val FiXED_10000_MILLISECOND = 10000L
    const val FiXED_30000_MILLISECOND = 30000L
    const val FIX_400_MILLISECOND = 400L
    const val FIX_500_MILLISECOND = 500L
    const val FIX_100_MILLISECOND = 100L
    const val FiXED_MINUS_13_INT = -13
    const val FiXED_1_INT = 1
    const val FiXED_2_INT = 2
    const val FiXED_3_INT = 3
    const val FiXED_4_INT = 4
    const val FiXED_5_INT = 5
    const val FiXED_6_INT = 6
    const val FiXED_8_INT = 8
    const val FiXED_9_INT = 9
    const val FiXED_10_INT = 10
    const val FiXED_12_INT = 12
    const val FiXED_16_INT = 16
    const val FiXED_20_INT = 20
    const val FiXED_24_INT = 24
    const val FiXED_29_INT = 29
    const val FiXED_50_INT = 50
    const val FiXED_60_INT = 60
    const val FiXED_90_INT = 90
    const val FiXED_100_INT = 100
    const val FiXED_130_INT = 130
    const val FiXED_150_INT = 150
    const val FiXED_200_INT = 200
    const val FiXED_230_INT = 230
    const val FiXED_300_INT = 300
    const val FiXED_365_INT = 365
    const val FIXED_500_INT = 500
    const val FiXED_1000_INT = 1000
    const val FiXED_3600_INT = 3600
    const val FiXED_1887_INT = 1887
    const val FiXED_1000000_INT = 1000000
    const val FiXED_30_FLOAT = 30.0f
    const val FiXED_50_FLOAT = 50F
    const val FiXED_100_FLOAT = 100.0f
    const val FiXED_210_FLOAT = 210.0f
    const val FiXED_MARGIN_40 = 40
    const val FIX_5000 = 5000

    // MessageType
    const val SHORTS = "shorts"
    const val GIFT = "gift"
    const val CHALLENGE = "challenge"
    const val FOLLOW = "Follow"
    const val HOST_INVITE = "host_invite"
    const val ALL = "All"
    const val COMMENT = "comment"
    const val SENT_YOU_FOLLOW_REQUEST = "sent you follow request"
    const val STRING_NULL = "null"
    const val COVER = "Cover"
    const val FOLDER = "Folder"
    const val TAP_TO_SELECT = "Tap to select"
    const val CAMERA = "Camera"
    const val MAXIMUM_4_LINES_ARE_ALLOWED = "Maximum 4 lines are allowed"
    const val TIME_FORMAT = "dd MMM yyyy,HH:mm a"
}
